version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: china-admin
    restart: unless-stopped
    tty: true
    command: bash
    volumes:
      - ./:/root/app
    ports:
      - 8125:8082

